---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections: 
upload_dir: app/public
public_path: app/public
front_matter_path: app/src/posts
use_front_matter_path: true
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
