---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Heading
- type: document
  path: app/src/posts
  label: Posts
upload_dir: app/public
public_path: ''
front_matter_path: app/src/posts
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv/app"
  instant_preview_command: npm run develop
